// import { Roboto } from 'next/font/google'
// import './globals.css'
// import { AntdRegistry } from '@ant-design/nextjs-registry'
// import StyledComponentsRegistry from '../regitsry'
// import Navbar from '../components/navbar'
// import Footer from '../components/footer/footer'

// const roboto = Roboto({
//   weight: ['400', '500', '700'], // Customize the weights you need
//   subsets: ['latin'], // Customize the subsets you need
//   variable: '--font-roboto', // Optional: to use as a CSS variable
// })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <link rel="preload" href="/globals.css" as="style" />
//         <link rel="stylesheet" href="/globals.css" /> {/* Add CSS here */}
//       </head>
//       <body style={{ padding: 0, margin: 0 }} className={roboto.className}>
//         <div className="home-fixednavbar-container">
//           <Navbar id="navbarfixed-navbar" rootClassName="navbarroot-class-name1"></Navbar>
//         </div>
//         <Navbar id="navbarstatic-navbar" rootClassName="navbarroot-class-name"></Navbar>
//         {children}
//         <Footer></Footer>
//       </body>
//     </html>
//   )
// }
import { Roboto } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import Navbar from '../components/navbar/navbar'
import Footer from '../components/footer/footer'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import '../globals.css'

const roboto = Roboto({
  weight: ['400', '500', '700'], // Customize the weights you need
  subsets: ['latin'], // Customize the subsets you need
  variable: '--font-roboto', // Optional: to use as a CSS variable
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function LocaleLayout({ children, params: { locale } }) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={`${roboto.className} body-container`}>
        <NextIntlClientProvider messages={messages}>
          <AntdRegistry>
            <div className="home-fixednavbar-container">
              <Navbar id="navbarfixed-navbar" rootClassName="navbarroot-class-name1"></Navbar>
            </div>
            <Navbar id="navbarstatic-navbar" rootClassName="navbarroot-class-name"></Navbar>
            {children}
            <Footer></Footer>
          </AntdRegistry>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
